# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestReleaseApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestReleaseApp
	pod 'TZImagePickerController'
  pod 'AsyncDisplayKit'
  target 'TestReleaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestReleaseAppUITests' do
    # Pods for testing
  end

end
