# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LXTextField' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LXTextField
 pod 'MJRefresh'
  pod 'LookinServer',:configurations => ['Debug']
  target 'LXTextFieldTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
